/*
 * generated by Xtext 2.12.0
 */
package hu.bme.mit.temalab.railmap.ide


/**
 * Use this class to register ide components.
 */
class RailLinesMapIdeModule extends AbstractRailLinesMapIdeModule {
}
