/*
 * generated by Xtext 2.12.0
 */
package hu.bme.mit.temalab.railmap.tests

import com.google.inject.Inject
import hu.bme.mit.temalab.railmap.railLinesMap.RailLineMap
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(RailLinesMapInjectorProvider)
class RailLinesMapParsingTest {
	@Inject
	ParseHelper<RailLineMap> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
