/*
 * generated by Xtext 2.12.0
 */
package hu.bme.mit.temalab.railmap


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RailLinesMapStandaloneSetup extends RailLinesMapStandaloneSetupGenerated {

	def static void doSetup() {
		new RailLinesMapStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
